vich_uploader:
  db_driver: orm

  mappings:
    fichier_import:
      uri_prefix: "%fichier_import%"
      upload_destination: "%kernel.project_dir%/public%fichier_import%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
